//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCSEntities1 : DbContext
    {
        public BCSEntities1()
            : base("name=BCSEntities1")
        {
        }

        public BCSEntities1(string connectionString)
            : base("name=BCSEntities1")
        {
            this.Database.Connection.ConnectionString = connectionString;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bin> Bins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<CPR> CPRs { get; set; }
        public virtual DbSet<GSS> GSSes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<QCSInfo> QCSInfoes { get; set; }
    }
}
