//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheSpot.EFStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string Subject { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Body { get; set; }
        public string temp1 { get; set; }
        public byte[] temp2 { get; set; }
        public byte[] temp3 { get; set; }
        public int ID { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
