//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheSpot.EFStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        public int ID { get; set; }
        public string BarCode { get; set; }
        public string Weight { get; set; }
        public string MaxWeight { get; set; }
        public int Category { get; set; }
        public int PhigidSlot { get; set; }
    
        public virtual Category Category1 { get; set; }
    }
}
