//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheSpot.EFStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPR
    {
        public int id { get; set; }
        public string store { get; set; }
        public int invoiceid { get; set; }
        public int state { get; set; }
        public string employeeID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string spare3 { get; set; }
    }
}
