//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheSpot.EFStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string BarCode { get; set; }
        public string State { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Note { get; set; }
        public string picture { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
