//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTheSpot.EFStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCSInfo
    {
        public int id { get; set; }
        public string HeatSeal { get; set; }
        public string Bin { get; set; }
        public System.DateTime Time { get; set; }
    }
}
